//! FilmCraft desktop app.
//!
//! Usage: `filmcraft [--control <port>] [--control-token <64-hex> | --control-token-file <path>]
//! [--demo|--empty] [--recover|--no-recover] [--data-dir <dir>] [project.fcproj | media files…]`
//!
//! Without a project, `--demo` or `--empty`, Settings ▸ General ▸ At Startup decides: Show Home
//! (the demo project), Open Most Recent, or an empty project.
//!
//! `--control <port>` (or `FILMCRAFT_CONTROL_PORT`) starts a localhost JSON-lines control server.
//! The first line on each connection must authenticate (`SECURITY.md`). With no token, a new one
//! is printed once; `--control-token-file` (or `FILMCRAFT_CONTROL_TOKEN_FILE`) loads or creates a
//! private file instead. See `filmcraft_ui_egui::control` for the methods.
//!
//! Auto-save and the crash-recovery journal run in every session (data in `--data-dir`, else
//! `FILMCRAFT_DATA_DIR`, else the per-user application data folder). If a previous session died
//! with unsaved changes the app asks to recover them; `--recover` recovers the newest without
//! asking, `--no-recover` starts without asking (the changes stay available via File ▸ Recover
//! Unsaved Changes…).

#![cfg_attr(not(test), deny(clippy::unwrap_used, clippy::expect_used, clippy::panic, clippy::unimplemented, clippy::todo, clippy::unreachable))]

mod app_nap;
mod audio;
mod audio_in;
mod control_server;
#[cfg(target_os = "macos")]
mod native_menu;
mod window_raise;

use chrono::TimeZone;
use filmcraft_engine::Session;
use filmcraft_engine::autosave::{AutosaveConfig, default_data_dir};
use filmcraft_ui_egui::FilmcraftApp;
use serde_json::json;

/// Reverse-DNS app id: Linux `.desktop` file, hicolor icon name and Wayland app id.
const APP_ID: &str = "ai.storyteller.filmcraft";

/// The window, Dock, taskbar and app-switcher icon (`assets/app-icon/`, regenerated by
/// `packaging/icons.sh`). macOS gets the tile inside Apple's transparent margin so it matches the
/// size of other Dock icons; Windows and Linux get the full-bleed tile.
fn app_icon() -> egui::IconData {
    #[cfg(target_os = "macos")]
    let png: &[u8] = include_bytes!("../../../assets/app-icon/filmcraft-macos-512.png");
    #[cfg(not(target_os = "macos"))]
    let png: &[u8] = include_bytes!("../../../assets/app-icon/hicolor/256x256/apps/ai.storyteller.filmcraft.png");
    eframe::icon_data::from_png_bytes(png).unwrap_or_default()
}

fn main() -> eframe::Result {
    app_nap::disable();
    let mut control_port: Option<u16> = std::env::var("FILMCRAFT_CONTROL_PORT").ok().and_then(|p| p.parse().ok());
    let mut control_token = None;
    let mut control_token_file = None;
    let mut files = Vec::new();
    let mut demo = true;
    // --demo / --empty given: skip Settings ▸ General ▸ At Startup
    let mut startup_flag = false;
    let mut recover: Option<bool> = None;
    let mut data_dir = None;
    let mut args = std::env::args().skip(1);
    while let Some(a) = args.next() {
        match a.as_str() {
            "--control" => control_port = args.next().and_then(|p| p.parse().ok()),
            "--control-token" => match args.next() {
                Some(token) => control_token = Some(token),
                None => {
                    eprintln!("filmcraft: --control-token requires a 64-character hexadecimal token");
                    return Ok(());
                }
            },
            "--control-token-file" => match args.next() {
                Some(path) => control_token_file = Some(std::path::PathBuf::from(path)),
                None => {
                    eprintln!("filmcraft: --control-token-file requires a path");
                    return Ok(());
                }
            },
            "--demo" => (demo, startup_flag) = (true, true),
            "--empty" => (demo, startup_flag) = (false, true),
            "--recover" => recover = Some(true),
            "--no-recover" => recover = Some(false),
            "--data-dir" => data_dir = args.next().map(std::path::PathBuf::from),
            "--version" => {
                println!("filmcraft {}", env!("CARGO_PKG_VERSION"));
                return Ok(());
            }
            _ => files.push(a),
        }
    }
    let control = if let Some(port) = control_port {
        let (supplied, token_file) = filmcraft_automation::security::token_inputs(control_token, control_token_file);
        let token = match filmcraft_automation::security::server_token(supplied.as_deref(), token_file.as_deref()) {
            Ok(token) => token,
            Err(e) => {
                eprintln!("filmcraft: cannot configure control authentication: {e}");
                return Ok(());
            }
        };
        if let Some(path) = &token_file {
            eprintln!("filmcraft: control token file: {}", path.display());
        } else if supplied.is_none() {
            // Printed once so the operator can hand it to a local bridge. Not written to disk.
            eprintln!("filmcraft: control token: {token}");
        } else {
            eprintln!("filmcraft: using supplied control token");
        }
        Some((port, token))
    } else {
        None
    };
    // Panics anywhere go to <data dir>/Logs/crash-<day>.log with a backtrace; the UI pass and
    // frame workers catch them and keep running (see filmcraft_ui_egui::crash).
    filmcraft_ui_egui::crash::install(data_dir.clone().or_else(default_data_dir).map(|d| d.join("Logs")));
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_title("FilmCraft")
            .with_inner_size([1600.0, 980.0])
            .with_min_inner_size([900.0, 560.0])
            .with_drag_and_drop(true)
            .with_fullsize_content_view(true)
            .with_titlebar_shown(false)
            .with_title_shown(false)
            // Started for an agent (`--control`): open without taking the user's keyboard focus.
            .with_active(control_port.is_none())
            .with_icon(app_icon())
            // Wayland matches the window to `packaging/linux/ai.storyteller.filmcraft.desktop`.
            .with_app_id(APP_ID),
        event_loop_builder: agent_event_loop(control_port.is_some()),
        ..Default::default()
    };
    let started = eframe::run_native(
        "FilmCraft",
        options,
        Box::new(move |cc| {
            let mut session = Session::default();
            if let Some(dir) = data_dir.clone().or_else(default_data_dir) {
                let mut cfg = AutosaveConfig::new(dir);
                cfg.local_offset = local_offset;
                if let Err(e) = session.start_autosave(cfg) {
                    eprintln!("filmcraft: auto-save and crash recovery unavailable: {e}");
                }
            }
            // voice-over recording reads the microphone through cpal
            session.voiceover.input = Some(Box::new(audio_in::CpalIn::new(&session.prefs.audio_hardware.device_class)));
            let project = files.iter().find(|f| f.ends_with(".fcproj")).cloned();
            if let Some(p) = project {
                if let Err(e) = session.execute("file.open", json!({"path": p})) {
                    eprintln!("filmcraft: {e}");
                }
            } else if !startup_flag && session.prefs.general.at_startup == "openMostRecent" {
                // Settings ▸ General ▸ At Startup ▸ Open Most Recent
                let recent = session.prefs.general.recent_projects.iter().find(|p| std::path::Path::new(p).exists()).cloned();
                match recent {
                    Some(p) => {
                        if let Err(e) = session.execute("file.open", json!({"path": p})) {
                            eprintln!("filmcraft: {e}");
                        }
                    }
                    None => {
                        let _ = session.execute("file.openDemoProject", json!({}));
                    }
                }
            } else if !startup_flag && session.prefs.general.at_startup == "emptyProject" {
            } else if demo {
                let _ = session.execute("file.openDemoProject", json!({}));
            }
            let media: Vec<String> = files.iter().filter(|f| !f.ends_with(".fcproj")).cloned().collect();
            if !media.is_empty() {
                let _ = session.execute("file.import", json!({"paths": media}));
            }
            if recover == Some(true) && !session.recovery_candidates().is_empty() {
                let id = session.recovery_candidates()[0].id.clone();
                match session.execute("file.recover", json!({"id": id})) {
                    Ok(r) => eprintln!("filmcraft: recovered {r}"),
                    Err(e) => eprintln!("filmcraft: recovery failed: {e}"),
                }
            }
            let mut app = FilmcraftApp::new(session);
            if recover == Some(false) {
                app.dialog = None;
            }
            app.integrated_titlebar = cfg!(target_os = "macos");
            if let Some(rs) = cc.wgpu_render_state.clone()
                && std::env::var_os("FILMCRAFT_CPU_COMPOSITE").is_none()
            {
                app.set_wgpu(rs);
            }
            if let Some(out) = audio::CpalOut::new() {
                // Settings ▸ Audio Hardware is applied on the first frame (`apply_prefs`)
                app.audio = Some(Box::new(out));
            }
            app.hooks.pick_files = Some(Box::new(|exts: &[&str]| {
                rfd::FileDialog::new().add_filter("Media", exts).pick_files().unwrap_or_default().into_iter().map(|p| p.to_string_lossy().to_string()).collect()
            }));
            app.hooks.pick_save = Some(Box::new(|name: &str| {
                rfd::FileDialog::new().add_filter("FilmCraft Project", &["fcproj"]).set_file_name(name).save_file().map(|p| p.to_string_lossy().to_string())
            }));
            app.hooks.pick_save_as = Some(Box::new(|filter: &str, exts: &[&str], name: &str| {
                rfd::FileDialog::new().add_filter(filter, exts).set_file_name(name).save_file().map(|p| p.to_string_lossy().to_string())
            }));
            app.hooks.pick_folder = Some(Box::new(|| rfd::FileDialog::new().pick_folder().map(|p| p.to_string_lossy().to_string())));
            app.hooks.open_path = Some(Box::new(open_path));
            app.hooks.raise_without_focus = Some(Box::new(|| {
                window_raise::raise_without_focus();
            }));
            app.hooks.pick_open_file = Some(Box::new(|filter: &str, exts: &[&str]| {
                rfd::FileDialog::new().add_filter(filter, exts).pick_file().map(|p| p.to_string_lossy().to_string())
            }));
            app.hooks.pick_open_project =
                Some(Box::new(|| rfd::FileDialog::new().add_filter("FilmCraft Project", &["fcproj"]).pick_file().map(|p| p.to_string_lossy().to_string())));
            #[cfg(target_os = "macos")]
            {
                let (rx, update) = native_menu::install(&app, cc.egui_ctx.clone());
                app.command_inbox = Some(rx);
                app.hooks.shortcuts_changed = Some(update);
                app.ui.show_menu_bar = false;
            }
            if let Some((port, token)) = control {
                let rx = control_server::start(port, token, cc.egui_ctx.clone());
                app = app.with_control(rx);
            }
            Ok(Box::new(app))
        }),
    );
    // The window could not be created (no usable GPU / graphics driver, no display): say so
    // instead of exiting silently, and keep the reason in the crash log.
    if let Err(e) = &started {
        let msg = format!("FilmCraft could not start its window: {e}\n\nUpdating the graphics driver usually fixes this.");
        eprintln!("filmcraft: {msg}");
        filmcraft_ui_egui::crash::record(&msg);
        let _ = rfd::MessageDialog::new().set_title("FilmCraft").set_description(&msg).set_level(rfd::MessageLevel::Error).show();
    }
    started
}

/// Open a file in its default application, or reveal it in the file manager (Edit Original,
/// Reveal Log Files).
fn open_path(path: &str, reveal: bool) -> Result<(), String> {
    let mut cmd = if cfg!(target_os = "macos") {
        let mut c = std::process::Command::new("open");
        if reveal {
            c.arg("-R");
        }
        c.arg(path);
        c
    } else if cfg!(target_os = "windows") {
        let mut c = std::process::Command::new("explorer");
        if reveal {
            c.arg(format!("/select,{path}"));
        } else {
            c.arg(path);
        }
        c
    } else {
        let mut c = std::process::Command::new("xdg-open");
        let p = std::path::Path::new(path);
        c.arg(if reveal { p.parent().unwrap_or(p) } else { p });
        c
    };
    cmd.spawn().map(|_| ()).map_err(|e| format!("can't open {path}: {e}"))
}

/// Local UTC offset at a unix time (auto-save file names and recovery times use local time).
fn local_offset(unix: i64) -> i32 {
    chrono::Local.timestamp_opt(unix, 0).single().map(|d| d.offset().local_minus_utc()).unwrap_or(0)
}

/// Driven by an agent (`--control`): don't activate the app on launch, so the user's keyboard
/// focus stays where it is (macOS; winit activates ignoring other apps by default).
fn agent_event_loop(agent: bool) -> Option<eframe::EventLoopBuilderHook> {
    #[cfg(target_os = "macos")]
    if agent {
        return Some(Box::new(|b| {
            use winit::platform::macos::EventLoopBuilderExtMacOS;
            b.with_activate_ignoring_other_apps(false);
        }));
    }
    let _ = agent;
    None
}
